spring.application.name=Grupo06

# Conexión a Base de Datos en la Nube (Supabase PostgreSQL)
# Usamos el modo de conexión directa / session pooler con prepareThreshold=0 para evitar conflictos con PgBouncer
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.qoupwzmfmsxtjasackkf
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_batch_fetch_size=20

# Documentación OpenAPI / Swagger
springdoc.swagger-ui.path=/swagger-ui.html
